<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TableQuantidadeVotoPorMunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('table_quantidade_voto_por_municipio')->insert([
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'SALVADOR', 'iQuantidadeVotos' => 6256, 'dPorcentagemVotos' => '12,43%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'FEIRA DE SANTANA', 'iQuantidadeVotos' => 4330, 'dPorcentagemVotos' => '8,6%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'PORTO SEGURO', 'iQuantidadeVotos' => 2284, 'dPorcentagemVotos' => '4,54%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'JUAZEIRO', 'iQuantidadeVotos' => 1901, 'dPorcentagemVotos' => '3,78%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'SANTO ANTÔNIO DE JESUS', 'iQuantidadeVotos' => 1401, 'dPorcentagemVotos' => '2,78%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'EUNÁPOLIS', 'iQuantidadeVotos' => 1345, 'dPorcentagemVotos' => '2,67%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'ITABUNA', 'iQuantidadeVotos' => 1338, 'dPorcentagemVotos' => '2,66%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'CAMAÇARI', 'iQuantidadeVotos' => 1199, 'dPorcentagemVotos' => '2,38%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'ILHÉUS', 'iQuantidadeVotos' => 1074, 'dPorcentagemVotos' => '2,13%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'TEIXEIRA DE FREITAS', 'iQuantidadeVotos' => 1044, 'dPorcentagemVotos' => '2,07%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'BARREIRAS', 'iQuantidadeVotos' => 1038, 'dPorcentagemVotos' => '2,06%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'LUÍS EDUARDO MAGALHÃES', 'iQuantidadeVotos' => 953, 'dPorcentagemVotos' => '1,89%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'SIMÕES FILHO', 'iQuantidadeVotos' => 761, 'dPorcentagemVotos' => '1,51%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'MUCURI', 'iQuantidadeVotos' => 727, 'dPorcentagemVotos' => '1,44%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'VITÓRIA DA CONQUISTA', 'iQuantidadeVotos' => 577, 'dPorcentagemVotos' => '1,15%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'ALAGOINHAS', 'iQuantidadeVotos' => 545, 'dPorcentagemVotos' => '1,08%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'ITAPETINGA', 'iQuantidadeVotos' => 475, 'dPorcentagemVotos' => '0,94%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'JEQUIÉ', 'iQuantidadeVotos' => 475, 'dPorcentagemVotos' => '0,94%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'CONCEIÇÃO DO COITÉ', 'iQuantidadeVotos' => 444, 'dPorcentagemVotos' => '0,88%'], 
            ['iIdFichaCadastralParlamentar' => 1, 'cNomeMunicipio' => 'NOVA VIÇOSA', 'iQuantidadeVotos' => 437, 'dPorcentagemVotos' => '0,87%'],  
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'SÃO PAULO', 'iQuantidadeVotos' => 38959, 'dPorcentagemVotos' => '56,25%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'EMBU DAS ARTES', 'iQuantidadeVotos' => 3027, 'dPorcentagemVotos' => '4,37%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'TABOÃO DA SERRA', 'iQuantidadeVotos' => 1936, 'dPorcentagemVotos' => '2,8%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'GUARULHOS', 'iQuantidadeVotos' => 1296, 'dPorcentagemVotos' => '1,87%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'OSASCO', 'iQuantidadeVotos' => 1031, 'dPorcentagemVotos' => '1,49%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'CAMPINAS', 'iQuantidadeVotos' => 853, 'dPorcentagemVotos' => '1,23%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'SANTO ANDRÉ', 'iQuantidadeVotos' => 836, 'dPorcentagemVotos' => '1,21%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'SÃO BERNARDO DO CAMPO', 'iQuantidadeVotos' => 663, 'dPorcentagemVotos' => '0,96%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'ITAPECERICA DA SERRA', 'iQuantidadeVotos' => 657, 'dPorcentagemVotos' => '0,95%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'DIADEMA', 'iQuantidadeVotos' => 552, 'dPorcentagemVotos' => '0,8%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'MARÍLIA', 'iQuantidadeVotos' => 524, 'dPorcentagemVotos' => '0,76%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'SÃO JOSÉ DOS CAMPOS', 'iQuantidadeVotos' => 517, 'dPorcentagemVotos' => '0,75%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'CARAPICUÍBA', 'iQuantidadeVotos' => 476, 'dPorcentagemVotos' => '0,69%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'COTIA', 'iQuantidadeVotos' => 470, 'dPorcentagemVotos' => '0,68%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'SOROCABA', 'iQuantidadeVotos' => 427, 'dPorcentagemVotos' => '0,62%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'JUNDIAÍ', 'iQuantidadeVotos' => 390, 'dPorcentagemVotos' => '0,56%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'SÃO JOSÉ DO RIO PRETO', 'iQuantidadeVotos' => 353, 'dPorcentagemVotos' => '0,51%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'PIRACICABA', 'iQuantidadeVotos' => 348, 'dPorcentagemVotos' => '0,5%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'FERRAZ DE VASCONCELOS', 'iQuantidadeVotos' => 336, 'dPorcentagemVotos' => '0,49%'], 
            ['iIdFichaCadastralParlamentar' => 2, 'cNomeMunicipio' => 'PRAIA GRANDE', 'iQuantidadeVotos' => 328, 'dPorcentagemVotos' => '0,47%'],
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'MACAPÁ', 'iQuantidadeVotos' => 10550, 'dPorcentagemVotos' => '55,2%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'SANTANA', 'iQuantidadeVotos' => 3668, 'dPorcentagemVotos' => '19,19%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'PORTO GRANDE', 'iQuantidadeVotos' => 927, 'dPorcentagemVotos' => '4,85%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'VITÓRIA DO JARI', 'iQuantidadeVotos' => 628, 'dPorcentagemVotos' => '3,29%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'OIAPOQUE', 'iQuantidadeVotos' => 590, 'dPorcentagemVotos' => '3,09%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'MAZAGÃO', 'iQuantidadeVotos' => 462, 'dPorcentagemVotos' => '2,42%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'CUTIAS', 'iQuantidadeVotos' => 443, 'dPorcentagemVotos' => '2,32%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'FERREIRA GOMES', 'iQuantidadeVotos' => 388, 'dPorcentagemVotos' => '2,03%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'LARANJAL DO JARI', 'iQuantidadeVotos' => 355, 'dPorcentagemVotos' => '1,86%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'CALÇOENE', 'iQuantidadeVotos' => 239, 'dPorcentagemVotos' => '1,25%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'SERRA DO NAVIO', 'iQuantidadeVotos' => 214, 'dPorcentagemVotos' => '1,12%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'ITAUBAL', 'iQuantidadeVotos' => 205, 'dPorcentagemVotos' => '1,07%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'PEDRA BRANCA DO AMAPARI', 'iQuantidadeVotos' => 152, 'dPorcentagemVotos' => '0,8%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'TARTARUGALZINHO', 'iQuantidadeVotos' => 133, 'dPorcentagemVotos' => '0,7%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'AMAPÁ', 'iQuantidadeVotos' => 126, 'dPorcentagemVotos' => '0,66%'], 
            ['iIdFichaCadastralParlamentar' => 3, 'cNomeMunicipio' => 'PRACUÚBA', 'iQuantidadeVotos' => 31, 'dPorcentagemVotos' => '0,16%'],
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'CASA NOVA', 'iQuantidadeVotos' => 4986, 'dPorcentagemVotos' => '4,86%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'SALVADOR', 'iQuantidadeVotos' => 4887, 'dPorcentagemVotos' => '4,76%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'ITAMARAJU', 'iQuantidadeVotos' => 4792, 'dPorcentagemVotos' => '4,67%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'JUAZEIRO', 'iQuantidadeVotos' => 4726, 'dPorcentagemVotos' => '4,61%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'MATA DE SÃO JOÃO', 'iQuantidadeVotos' => 4192, 'dPorcentagemVotos' => '4,09%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'FEIRA DE SANTANA', 'iQuantidadeVotos' => 4023, 'dPorcentagemVotos' => '3,92%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'VITÓRIA DA CONQUISTA', 'iQuantidadeVotos' => 3982, 'dPorcentagemVotos' => '3,88%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'CURAÇÁ', 'iQuantidadeVotos' => 3367, 'dPorcentagemVotos' => '3,28%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'SENTO SÉ', 'iQuantidadeVotos' => 3324, 'dPorcentagemVotos' => '3,24%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'BARRA', 'iQuantidadeVotos' => 3123, 'dPorcentagemVotos' => '3,04%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'VALENTE', 'iQuantidadeVotos' => 2711, 'dPorcentagemVotos' => '2,64%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'JAGUARARI', 'iQuantidadeVotos' => 2653, 'dPorcentagemVotos' => '2,59%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'BOA VISTA DO TUPIM', 'iQuantidadeVotos' => 2610, 'dPorcentagemVotos' => '2,54%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'TEIXEIRA DE FREITAS', 'iQuantidadeVotos' => 2487, 'dPorcentagemVotos' => '2,42%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'ITORORÓ', 'iQuantidadeVotos' => 2298, 'dPorcentagemVotos' => '2,24%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'EUNÁPOLIS', 'iQuantidadeVotos' => 2012, 'dPorcentagemVotos' => '1,96%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'ITABUNA', 'iQuantidadeVotos' => 1806, 'dPorcentagemVotos' => '1,76%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'POJUCA', 'iQuantidadeVotos' => 1686, 'dPorcentagemVotos' => '1,64%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'BURITIRAMA', 'iQuantidadeVotos' => 1554, 'dPorcentagemVotos' => '1,51%'], 
            ['iIdFichaCadastralParlamentar' => 4, 'cNomeMunicipio' => 'SANTA RITA DE CÁSSIA', 'iQuantidadeVotos' => 1539, 'dPorcentagemVotos' => '1,5%'],
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SÃO PAULO', 'iQuantidadeVotos' => 35461, 'dPorcentagemVotos' => '55,11%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'CAMPINAS', 'iQuantidadeVotos' => 2046, 'dPorcentagemVotos' => '3,18%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SÃO BERNARDO DO CAMPO', 'iQuantidadeVotos' => 1526, 'dPorcentagemVotos' => '2,37%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'OSASCO', 'iQuantidadeVotos' => 1508, 'dPorcentagemVotos' => '2,34%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SANTO ANDRÉ', 'iQuantidadeVotos' => 1371, 'dPorcentagemVotos' => '2,13%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'GUARULHOS', 'iQuantidadeVotos' => 1202, 'dPorcentagemVotos' => '1,87%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SÃO JOSÉ DOS CAMPOS', 'iQuantidadeVotos' => 752, 'dPorcentagemVotos' => '1,17%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'JUNDIAÍ', 'iQuantidadeVotos' => 641, 'dPorcentagemVotos' => '1%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'RIBEIRÃO PRETO', 'iQuantidadeVotos' => 593, 'dPorcentagemVotos' => '0,92%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SOROCABA', 'iQuantidadeVotos' => 588, 'dPorcentagemVotos' => '0,91%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'BARUERI', 'iQuantidadeVotos' => 549, 'dPorcentagemVotos' => '0,85%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SÃO CAETANO DO SUL', 'iQuantidadeVotos' => 536, 'dPorcentagemVotos' => '0,83%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SANTOS', 'iQuantidadeVotos' => 500, 'dPorcentagemVotos' => '0,78%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'COTIA', 'iQuantidadeVotos' => 438, 'dPorcentagemVotos' => '0,68%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'CARAPICUÍBA', 'iQuantidadeVotos' => 411, 'dPorcentagemVotos' => '0,64%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SANTANA DE PARNAÍBA', 'iQuantidadeVotos' => 402, 'dPorcentagemVotos' => '0,62%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'MOGI DAS CRUZES', 'iQuantidadeVotos' => 396, 'dPorcentagemVotos' => '0,62%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'TABOÃO DA SERRA', 'iQuantidadeVotos' => 396, 'dPorcentagemVotos' => '0,62%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'PIRACICABA', 'iQuantidadeVotos' => 381, 'dPorcentagemVotos' => '0,59%'], 
            ['iIdFichaCadastralParlamentar' => 5, 'cNomeMunicipio' => 'SÃO JOSÉ DO RIO PRETO', 'iQuantidadeVotos' => 378, 'dPorcentagemVotos' => '0,59%'],        
        ]);
    }
}
